### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by wnehm** [data-8/data8assets#5]
![image](https://user-images.githubusercontent.com/22519312/38620549-44bf92f2-3dd1-11e8-9576-b9b267396869.png)
I am a Chinese postgraduate. Recently, I was studying _Foundations of Data Science_ in _Data 8_. I have cloned and downloaded the complete zip. But when I do the homework by jupyter, the _ModuleNotFoundError_ is jumped out. So what should I do?

**Comment by ryanlovett** [comment]
The client library is provided by [okpy](https://pypi.python.org/pypi/okpy) and is for submitting assignments for grading. If you're not enrolled in a Berkeley class, this step and all other "ok" functions may be skipped.

The most recent course materials are at https://github.com/data-8/materials-sp18.

You can run the course notebooks reproducibly by clicking the INTERACT links in the [textbook](https://www.inferentialthinking.com/). These launch notebooks on mybinder.org.

You may also be interested in [Data 8X](https://data.berkeley.edu/education/data-8x), a free, online version of the course which provides access to a hosted Jupyter server.

**Comment by wnehm** [comment]
OK, I know. 

Thanks for your detailed reply.
